---
- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: yes

- name: Install Maven
  apt:
    name: maven
    state: latest
    update_cache: yes

- name: Set MySQL root password
  debconf:
    name: "mysql-server"
    question: "mysql-server/root_password"
    value: "{{mysql_password}}"
    vtype: "password"
  become: true

- name: Confirm MySQL root password
  debconf:
    name: "mysql-server"
    question: "mysql-server/root_password_again"
    value: "{{mysql_password}}"
    vtype: "password"
  become: true

- name: Download and install packages
  apt:
    name: [mysql-server, python-mysqldb, python-apt, python-dev, mysql-client]
    update_cache: yes
  become: yes

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  become: yes

- name: insert skip grant tables in my.cnf
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    insertafter: "skip-external-locking"
    line: "skip-grant-tables"
  become: true

- name: Restart the MySQL service
  become: yes
  service:
    name: mysql
    state: restarted
    enabled: true

- name: Downloading the Google Chrome package for Ubuntu
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /

- name: Install google chrome on the Jenkins server using .deb
  apt:
    deb: "/google-chrome-stable_current_amd64.deb"

- name: Configure timezone
  timezone:
    name: America/New_York

# - name: Copy iTrust repo configurations
#   template:
#     src: iTrustBuild.Unix.sh
#     dest: /
    # force: yes

- name: set environment variables - GH User
  lineinfile:
    dest: /etc/environment
    line: GH_USER={{GH_USER}}
    regexp: "^GH_USER="
    state: present

- name: set environment variables - GH Password
  lineinfile:
    dest: /etc/environment
    line: GH_PASS={{GH_PASS}}
    regexp: "^GH_PASS="
    state: present

- name: Source environment variables
  shell: . /etc/environment

- name: remove Itrust
  file:
    path: '{{iTrust_home}}'
    state: absent

- name: clone iTrust
  git: 
    repo: 'https://{{GH_USER}}:{{GH_PASS}}@github.ncsu.edu/engr-csc326-staff/iTrust2-v6.git'
    dest: '{{iTrust_home}}'
    update: no
- name: remove configes
  file:
    path: /iTrust2-v6/iTrust2/src/main/java/db.properties.template
    state: absent
- name: remove configes
  file:
    path: /iTrust2-v6/iTrust2/src/main/java/email.properties.template
    state: absent

- name: Copying the new email.properties with updated credentials
  template:
    src: "{{ project_directory }}/roles/iTrust_envi/templates/email.properties.j2"
    dest: /iTrust2-v6/iTrust2/src/main/java/email.properties
    force: yes

- name: Copying the new db.properties with updated credentials
  template:
    src: "{{ project_directory }}/roles/iTrust_envi/templates/db.properties.j2"
    dest: /iTrust2-v6/iTrust2/src/main/java/db.properties
    force: yes


# - name: Configure iTrust
  # shell: bash /iTrustBuild.Unix.sh

- name: stat for /opt/tomcat9
  stat:
    path: /opt/tomcat9
  register: tomcatPath

- name: Get tomcat installation tar
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.0.M27/bin/apache-tomcat-9.0.0.M27.tar.gz
    dest: /opt
  when: tomcatPath.stat.exists == False

- name: Unzip the tar
  unarchive:
    remote_src: yes
    src: /opt/apache-tomcat-9.0.0.M27.tar.gz
    dest: /opt
  when: tomcatPath.stat.exists == False

- name: Rename the extracted tar
  command: mv apache-tomcat-9.0.0.M27 tomcat9
  args:
    chdir: /opt
  when: tomcatPath.stat.exists == False

- name: Set CATALINA_HOME environment variables
  lineinfile:
    path: /etc/environment
    line: CATALINA_HOME="/opt/tomcat9"
    state: present
    insertafter: EOF

- name: Update the bash profile
  shell: . /etc/environment

- name: Copy tomcat config file
  copy:
    src: tomcat-users.xml
    dest: /opt/tomcat9/conf/tomcat-users.xml
    mode: 0500

- name: Copy tomcat war file
  copy:
    src: "/bakerx/deploy/roles/iTrust/templates/iTrust2.war"
    dest: /opt/tomcat9/webapps/
    force: yes

- name: Start Tomcat
  shell: nohup sh /opt/tomcat9/bin/startup.sh

# - name: download test cases
#   shell: cd /iTrust2-v6/iTrust2/ && sudo mvn -f pom-data.xml process-test-classes

- name: download test cases
  shell: mvn -f pom-data.xml process-test-classes
  args:
    chdir: /iTrust2-v6/iTrust2/

