- name: Copy folder
  copy:
    src: /bakerx/provision/roles/webserver_setup/templates/agent
    dest: "{{ aws_home }}"

- name: Set environment variable - VMNAME
  lineinfile:
    dest: /etc/environment
    line: VMNAME={{ vmname }}
    regexp: '^VMNAME'
    state: present

- name: Install npm packages
  npm:
    path: /home/ubuntu/agent

- name: Install forever
  npm:
    name: forever
    global: true
    state: latest

- name: Source environment variables
  shell: . /etc/environment

- name: run agent/index.js forever
  shell: "cd {{ aws_home }}/agent && forever stopall && forever start index.js"