---

- name: Ensure Redis is present
  apt: 
    name: redis-server
    state: latest

- name: Ensure Redis is started
  service: 
    name: redis-server
    state: started
    enabled: yes

- name: Ensure Redis Configuration
  template: 
    src: redis.conf.j2 
    dest: /etc/redis/redis.conf 
    owner: root 
    group: root 
    mode: 0644
  notify: Redis Restart

- name: Copy folder
  copy:
    src: /bakerx/provision/roles/monitor_setup/templates/dashboard
    dest: "{{ aws_home }}"

- name: copy monitor_ip.txt
  shell: "cp {{ aws_home }}/monitor_ip.txt {{ aws_home }}/dashboard/metrics/ip.txt"

- name: Install npm packages
  npm:
    path: "{{ aws_home }}/dashboard"

- name: Install forever
  npm:
    name: forever
    global: true
    state: latest

- name: Copy the iTrust IP
  copy:
    src: "/bakerx/results/192.168.33.20{{ jenkins_home }}/itrust_ip.txt"
    dest: "{{ aws_home }}"

- name: Load data
  slurp:
    src: "{{ aws_home }}/itrust_ip.txt"
  register: slurped_user_data

- name: debug
  debug:
    msg: "{{ slurped_user_data['content'] | b64decode }}"

- name: set environment variables - ITRUST_IP
  lineinfile:
    dest: /etc/environment
    line: ITRUST_IP={{ slurped_user_data['content'] | b64decode }}
    regexp: '^ITRUST_IP'
    state: present

- name: Copy the Checkbox IP
  copy:
    src: "/bakerx/results/192.168.33.20{{ jenkins_home }}/checkbox_ip.txt"
    dest: "{{ aws_home }}"

- name: Load data
  slurp:
    src: "{{ aws_home }}/checkbox_ip.txt"
  register: slurped_user_data

- name: debug
  debug:
    msg: "{{ slurped_user_data['content'] | b64decode }}"

- name: set environment variables - CHECKBOX_IP
  lineinfile:
    dest: /etc/environment
    line: CHECKBOX_IP={{ slurped_user_data['content'] | b64decode }}
    regexp: '^CHECKBOX_IP'
    state: present

- name: Source environment variables
  shell: . /etc/environment

- name: Run bin/www forever
  shell: "cd {{ aws_home }}/dashboard && forever stopall && forever start bin/www"

