---

- name: Ensure Redis is present
  apt: 
    name: redis-server
    state: latest

- name: Ensure Redis is started
  service: 
    name: redis-server
    state: started
    enabled: yes

- name: Ensure Redis Configuration
  template: 
    src: redis.conf.j2 
    dest: /etc/redis/redis.conf 
    owner: root 
    group: root 
    mode: 0644
  notify: Redis Restart

- name: Copy folder
  copy:
    src: /bakerx/provision/roles/monitor_setup/templates/dashboard
    dest: /home/ubuntu/

- name: copy ip.txt
  shell: cp /home/ubuntu/ip.txt /home/ubuntu/dashboard/metrics/

- name: Install npm packages
  npm:
    path: /home/ubuntu/dashboard

- name: Install forever
  npm:
    name: forever
    global: true
    state: latest

