---   
- name: Adding Apt Key For Jenkins
  apt_key:
    url: "https://jenkins-ci.org/debian/jenkins-ci.org.key"
    state: present
  become: true

- name: Check For Jenkins List    
  stat: path=/etc/apt/sources.list.d/jenkins.list
  register: jenkins_list

- name: Adding Jenkins Source List
  shell: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
  when: not jenkins_list.stat.exists
  become: true

- name: Installing Jenkins
  apt:
    name: jenkins     
    state: present
    update_cache: yes
  register: jenkins_install
  become: true

- name: Restarting Jenkins
  service:
    name: jenkins
    state: restarted
  become: true

- name: Configure Jenkins port
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^HTTP_PORT=8080'
    line: 'HTTP_PORT=9000'
  become: true

- name: Restarting Jenkins
  service:
    name: jenkins
    state: restarted
  become: true


