---   
- name: Add Java 8 repository
  apt_repository: repo='ppa:webupd8team/java'
  become: yes

- name: Update APT-GET
  shell: apt-get update
  become: true

- name: Agree to Oracle license
  debconf: name=openjdk-8-jdk-headless question=shared/accepted-oracle-license-v1-1 vtype=select value=true
  become: yes

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - openjdk-8-jdk-headless

- name: Update apt-get
  action: apt update_cache=yes
  become: true

