---
- name: Install the boto3 python package
  pip:
    name: boto3
    state: present

- name: Install the aws-cli
  pip:
    name: awscli
    state: present

- name: Make provision directory
  file:
    path: "{{ jenkins_homeuser_path }}/provision"
    state: directory

- name: Make .aws directory
  file:
    path: "{{ jenkins_homeuser_path }}/.aws"
    state: directory
    owner: vagrant
    group: vagrant

- name: Copy vm creation python program
  copy:
    src: /bakerx/cm/roles/provision_envi/templates/create_aws_vm.py
    dest: "{{ jenkins_homeuser_path }}/provision"

- name: Copy aws_config
  template:
    src: /bakerx/cm/roles/provision_envi/templates/aws_config.j2
    dest: "{{ jenkins_homeuser_path }}/.aws/config"

- name: Copy aws_credentials
  template:
    src: /bakerx/cm/roles/provision_envi/templates/aws_credentials.j2
    dest: "{{ jenkins_homeuser_path }}/.aws/credentials"

- name: Save REGION as environment variable
  lineinfile:
    dest: /etc/environment
    line: AWS_REGION={{ AWS_REGION }}
    regexp: '^AWS_REGION'
    state: present

- name: Save AWS SECRET ACCESS KEY as environment variable
  lineinfile:
    dest: /etc/environment
    line: AWS_SECRET_ACCESS_KEY={{ AWS_SECRET_ACCESS_KEY }}
    regexp: '^AWS_SECRET_ACCESS_KEY'
    state: present

- name: Save ACCESS KEY ID as environment variable
  lineinfile:
    dest: /etc/environment
    line: AWS_ACCESS_KEY_ID={{ AWS_ACCESS_KEY_ID }}
    regexp: '^AWS_ACCESS_KEY_ID'
    state: present

- name: Copy key to jenkins-srv
  copy:
    src: /bakerx/cm/roles/provision_envi/templates/ec2-KP-devops06.pem
    dest: "{{ jenkins_homeuser_path }}/ec2-KP-devops06.pem"
