---
# see the best practices in ansible docs for how to get started with creating roles etc.:
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html

- hosts: monitor-vm
  gather_facts: false
  become: yes
  vars_files:
    - /bakerx/cm/vars/vars.yml
  tasks:
    - name: npm install
      shell: cd /home/vagrant/proxy/ && npm install

    - name: Run proxy.js
      shell: cd /home/vagrant/proxy/ && node proxy.js

    - name: Read Canary report
      slurp:
        src: /home/vagrant/canaryAnalysis.txt
      register: canary_report

    - name: Display the report
      debug:
        msg: "{{ canary_report['content'] | b64decode }}"

  vars:
    ansible_python_interpreter: python
