---
- hosts: monitor-vm
  gather_facts: false
  become: yes
  vars_files:
    - /bakerx/cm/vars/vars.yml
  tasks:
    - name: update
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: "3600"


- hosts: blue
  gather_facts: false
  become: yes
  vars_files:
    - /bakerx/cm/vars/vars.yml
  tasks:
    - name: update
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: "3600"

- hosts: green
  gather_facts: false
  become: yes
  vars_files:
    - /bakerx/cm/vars/vars.yml
  tasks:
    - name: update
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: "3600"
