---
- name: Install Python
  raw: apt-get -y install python

- name: Update
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: add apt key for nodesource
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add ppa for installing nodejs
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  register: node_repo

- name: Update apt cache if repo was added.
  apt:
    update_cache: yes
  when: node_repo.changed
  tags: ["skip_ansible_lint"]

- name: Install Nodejs
  apt:
    name: nodejs

- name: Install Git
  apt:
    name: git

- name: Make proxy directory
  file:
    path: "{{ jenkins_homeuser_path }}/proxy"
    state: directory

- name: Copy proxy.js code
  template:
    src: /bakerx/canary/roles/proxy/templates/proxy.js
    dest: "{{ jenkins_homeuser_path }}/proxy"

- name: Copy package.json file
  template:
    src: /bakerx/canary/roles/proxy/templates/package.json
    dest: "{{ jenkins_homeuser_path }}/proxy"

- name: Do npm install
  npm:
    path: /home/vagrant/proxy
  become: true

- name: Ensure Redis is present
  apt: 
    name: redis-server
    state: latest

- name: Ensure Redis is started
  service: 
    name: redis-server
    state: started
    enabled: yes

- name: Ensure Redis Configuration
  template: 
    src: redis.conf.j2 
    dest: /etc/redis/redis.conf 
    owner: root 
    group: root 
    mode: 0644
  notify: Redis Restart

- name: Run proxy.js
  shell: |
    cd /home/vagrant/proxy
    node proxy.js
