---
- name: Update
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: add apt key for nodesource
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add ppa for installing nodejs
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  register: node_repo

- name: Update apt cache if repo was added.
  apt:
    update_cache: yes
  when: node_repo.changed
  tags: ["skip_ansible_lint"]

- name: Install Nodejs
  apt:
    name: nodejs

- name: Install Git
  apt:
    name: git

- name: Make proxy directory
  file:
    path: "{{ jenkins_homeuser_path }}/proxy"
    state: directory

- name: Copy proxy.js code
  template:
    src: /bakerx/canary/roles/proxy/templates/proxy.js
    dest: "{{ jenkins_homeuser_path }}/proxy"

- name: Copy stableServer IP file
  template:
    src: /bakerx/canary/roles/proxy/templates/stableServer
    dest: "{{ jenkins_homeuser_path }}/proxy"

- name: Copy canaryServer IP file
  template:
    src: /bakerx/canary/roles/proxy/templates/canaryServer
    dest: "{{ jenkins_homeuser_path }}/proxy"

- name: Copy package.json file
  template:
    src: /bakerx/canary/roles/proxy/templates/package.json
    dest: "{{ jenkins_homeuser_path }}/proxy"

- name: Do npm install
  shell: npm install
  args:
    chdir: /home/vagrant/proxy
