---
- name: Running the Build job for Checkbox
  command: java -jar ~/jenkins-cli.jar -s http://{{ jenkins_username }}:{{ jenkins_password }}@localhost:9000/ build {{ checkbox_job_name }} -s
  ignore_errors: true
  
- name: Get the logs and save in the register
  command: java -jar ~/jenkins-cli.jar -s http://admin:admin@localhost:9000/ command checkbox_job
  register: log
  
- name: Show log
  debug:
    msg: "{{ log.stdout_lines }}"
