---
- name: Update
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: add ppa for installing nodejs
  shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

- name: Install Nodejs
  apt: name=nodejs

- name: Install Git
  apt:
    name: git

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Import the public key used by the package management system
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10 state=present

- name: Add MongoDB repository
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present

- name: install mongodb
  apt: pkg=mongodb-org state=latest update_cache=yes
  notify:
  - start mongodb

# - name: Add Mongo packages repo
#   apt_key: 
#     id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5  
#     keyserver: keyserver.ubuntu.com

# - name: add repo itself
#   apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/3.4 multiverse' state=present                                      
# - name: install packages
#   apt: pkg=mongodb-org state=present