---
- name: Running the Build job for Checkbox
  command: java -jar ~/jenkins-cli.jar -s http://admin:admin@localhost:9000/ build checkbox_job -s
  
- name: Get the logs and save in the register
  command: java -jar ~/jenkins-cli.jar -s http://admin:admin@localhost:9000/ command checkbox_job
  register: log
  
- name: Show log
  debug:
    msg: "{{ log }}"
