---
# see the best practices in ansible docs for how to get started with creating roles etc.: 
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html

- hosts: jenkins
  gather_facts: false
  become: yes
  vars_files:
   - ./vars/vars.yml
  tasks: 
  - name: "Copy ansible-srv:/bakerx/Fuzzer to jenkins-srv:/home/vagrant/Fuzzer"
    copy:
      src: /bakerx/Fuzzer
      dest: "{{ jenkins_homeuser_path }}"


  - name: install node packages in /home/vagrant/Fuzzer
    npm:
      path: "{{ jenkins_homeuser_path }}Fuzzer"
      
  - name: Run iTrust test {{check}} time(s)
    shell: node {{ jenkins_homeuser_path }}/Fuzzer/FS.js {{check}}

  - name: fetch
    fetch:
      src: "{{ jenkins_homeuser_path }}/result.txt"
      dest: /bakerx/results

  - name: Print results
    debug: var=item
    with_file:
      - "/bakerx/results/192.168.33.20{{ jenkins_homeuser_path }}/result.txt"
  
      
