---
- name: Running the Build job for Itrust
  command: java -jar ~/jenkins-cli.jar -s http://{{ jenkins_username }}:{{ jenkins_password }}@localhost:9000/ build {{ itrust_job_name }} -s
  ignore_errors: true
  
- name: Get the logs and save in the register
  command: java -jar ~/jenkins-cli.jar -s http://{{ jenkins_username }}:{{ jenkins_password }}@localhost:9000/ console {{ itrust_job_name }}
  register: log
  
- name: Show log
  debug:
    msg: "{{ log.stdout_lines }}"
