---
- name: Install Python
  raw: sudo apt-get -y install python

- name: Update
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: add ppa for installing nodejs
  shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

- name: Install Nodejs
  apt: 
    name: nodejs

- name: Install Git
  apt:
    name: git

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: install gnupg
  apt:
    name: gnupg
    state: present

- name: GPG key
  shell: wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -

- name: create list file for mongo
  shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list

- name: Install mongo
  apt: pkg=mongodb-org state=latest update_cache=yes
  notify: 
  - start mongodb
    
- name: Installing Python-Pip
  apt:
    name: python-pip
    state: latest

- name: Install the latest pymongo package
  pip: 
    name: pymongo
    state: present

- name: start mongodb
  systemd: 
    name: mongod 
    state: started

- name: Create mongodb Database and User
  mongodb_user:
    database: admin
    name: "admin"
    password: "admin"
    state: present
    roles: readWrite

- debug:
    msg:
    - "{{ MONGO_PORT }}"
    - "{{ APP_PORT }}"
    - "{{ MONGO_IP }}"
    - "{{ MONGO_USER }}"
    - "{{ MONGO_PASSWORD }}"
    
