---
- name: Install Python
  raw: apt-get -y install python

- name: Update
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: add ppa for installing nodejs
  shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

- name: Install Nodejs
  apt: 
    name: nodejs

- name: Install Git
  apt:
    name: git

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: install gnupg
  apt:
    name: gnupg
    state: present

- name: Import the public key
  apt_key: 
    keyserver: hkp://keyserver.ubuntu.com:80 
    id: 4B7C549A058F8B6B 
    state: present
  
- name: Add MongoDB repository
  apt_repository: 
    repo: deb http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse
    state: present

- name: install mongodb
  apt: pkg=mongodb-org state=latest update_cache=yes
  notify: 
  - start mongodb

    
- name: Installing Python-Pip
  apt:
    name: python-pip
    state: latest

- name: Install the latest pymongo package
  pip: 
    name: pymongo
    state: present

- name: start mongodb
  systemd: 
    name: mongod 
    state: started

- name: Create mongodb Database and User
  mongodb_user:
    database: admin
    name: "admin"
    password: "admin"
    state: present
    roles: readWrite


- name: set environment variables
  lineinfile:
    dest: /etc/environment
    line: APP_PORT="{{APP_PORT}}"
    insertafter: 'EOF' 
    state: present
  
  
- name: set environment variables
  lineinfile:
    dest: /etc/environment
    line: MONGO_PORT="{{MONGO_PORT}}"
    insertafter: 'EOF' 
    state: present
  

- name: set environment variables
  lineinfile:
    dest: /etc/environment
    line: MONGO_IP="{{MONGO_IP}}"
    insertafter: 'EOF' 
    state: present

- name: set environment variables
  lineinfile:
    dest: /etc/environment
    line: MONGO_USER="{{MONGO_USER}}"
    insertafter: 'EOF' 
    state: present

- name: set environment variables
  lineinfile:
    dest: /etc/environment
    line: MONGO_PASSWORD="{{MONGO_PASSWORD}}"
    insertafter: 'EOF' 
    state: present

- name: set environment variables
  lineinfile:
    dest: /etc/environment
    line: BUILD_ID=dontKillMe
    insertafter: 'EOF' 
    state: present

- name: Source environment variables
  shell: . /etc/environment

- debug:
    msg:
    - "{{ MONGO_PORT }}"
    - "{{ APP_PORT }}"
    - "{{ MONGO_IP }}"
    - "{{ MONGO_USER }}"
    - "{{ MONGO_PASSWORD }}"
    
