---

- name: Copy the key
  copy:
    src: /home/vagrant/192.168.33.20/home/vagrant/ec2-KP-devops06.pem
    dest: /home/ubuntu/.ssh/ec2-KP-devops06
    owner: ubuntu
    group: ubuntu
    mode: u=r--,g=---,o=---

- name: Copy the IP
  copy:
    src: /bakerx/results/192.168.33.20/home/vagrant/ip.txt
    dest: /home/ubuntu/

- name: Load data
  slurp:
    src: /home/ubuntu/ip.txt
  register: slurped_user_data

- name: debug
  debug:
    msg: "{{ slurped_user_data['content'] | b64decode }}"

- name: set environment variables - MONITOR_IP
  lineinfile:
    dest: /etc/environment
    line: MONITOR_IP={{ slurped_user_data['content'] | b64decode }}
    regexp: '^MONITOR_IP'
    state: present

- name: Update
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: "3600"

- name: add apt key for nodesource
  apt_key: 
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add ppa for installing nodejs
  apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes
  register: node_repo


- name: Update apt cache if repo was added.
  apt: 
    update_cache: yes
  when: node_repo.changed
  tags: ['skip_ansible_lint']

- name: Install Nodejs
  apt: 
    name: nodejs

- name: Install Git
  apt:
    name: git

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: install gnupg
  apt:
    name: gnupg
    state: present