---

- name: provision VM(s)
  shell: python {{ jenkins_homeuser_path }}/provision/create_aws_vm.py
  become: true

- name: Copy jenkins-srv:/home/vagrant/provision/
  fetch:
    src: "{{ jenkins_homeuser_path }}/deploy.ini"
    dest: /bakerx/results
    