---   
- name: Adding Apt Key For Jenkins
  apt_key:
    url: "https://jenkins-ci.org/debian/jenkins-ci.org.key"
    state: present
  become: true

- name: Check For Jenkins List    
  stat: 
    path: /etc/apt/sources.list.d/jenkins.list
  register: jenkins_list

- name: Adding Jenkins Source List
  shell: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
  when: not jenkins_list.stat.exists
  become: true

- name: Installing Jenkins
  apt:
    name: jenkins     
    state: present
    update_cache: yes
  become: true

- name: Configure Jenkins port
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^HTTP_PORT=8080'
    line: 'HTTP_PORT=9000'
  become: true

- name: Restarting Jenkins
  service:
    name: jenkins
    state: restarted
  become: true

- name: Wait while re-starting Jenkins
  wait_for: 
    port: 9000 
    delay: 30

- name: Create Directory For Groovy Script - Jenkins
  file:
    path: "{{jenkins_path}}/init.groovy.d"
    state: directory
    mode: 0755
  register: groovy_dir
  become: true

- name: Copying Groovy Script For Deafult Jenkins User(ADMIN) Creation
  template:
    force: yes
    src: "{{ project_directory }}/roles/jenkins/templates/jenkins_user.groovy.j2"
    dest: "{{jenkins_path}}/init.groovy.d/basic-security.groovy"
    mode: 0755
  become: true

- name: Jenkin Plugins installation
  jenkins_plugin:
    name: "{{ item }}"
    url_username: "{{jenkins_username}}"
    url_password: "{{jenkins_password}}"
    url: "{{jenkins_url}}"
  with_items:
    - github
    - postbuildscript
    - build-timeout
    - postbuild-task
    - ws-cleanup
    - jenkins-job-builder
    - html-xml-utils
  ignore_errors: yes

- name: Restarting Jenkins
  service:
    name: jenkins
    state: restarted
  become: true

- name: Wait while re-starting Jenkins
  wait_for: 
    port: 9000 
    delay: 30

- name: Removing Groovy Script so it doesn't create furthermore user
  file:
    path: "{{jenkins_path}}/init.groovy.d/basic-security.groovy"
    state: absent
  become: true
