---
- name: Update
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: add apt key for nodesource
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add ppa for installing nodejs
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  register: node_repo

- name: Update apt cache if repo was added.
  apt:
    update_cache: yes
  when: node_repo.changed
  tags: ["skip_ansible_lint"]

- name: Install Nodejs
  apt:
    name: nodejs

- name: Install Git
  apt:
    name: git

- name: Install forever
  npm:
    name: forever
    global: true
    state: latest

- name: Clone the repository
  git:
    repo: "https://github.com/chrisparnin/checkbox.io-micro-preview.git"
    dest: /home/vagrant/checkbox
  become: true

- name: Do npm install
  npm:
    path: /home/vagrant/checkbox

- name: run forever
  shell: "cd /home/vagrant/checkbox && forever stopall && git checkout {{branch}} && forever start index.js"
