---
- name: Wait for system to become reachable
  wait_for_connection:
    timeout: 120

# - name: Install Python
#   raw: apt-get -y install python3

- name: Update
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: "3600"

- name: add apt key for nodesource
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add ppa for installing nodejs
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  register: node_repo

- name: Update apt cache if repo was added.
  apt:
    update_cache: yes
  when: node_repo.changed
  tags: ["skip_ansible_lint"]

- name: Install Nodejs
  apt:
    name: nodejs

- name: Install Git
  apt:
    name: git

- name: Install forever
  npm:
    name: forever
    global: true
    state: latest

- name: Clone the repository
  git:
    repo: "https://github.com/chrisparnin/checkbox.io-micro-preview.git"
    dest: "{{ jenkins_homeuser_path }}/checkbox"
  become: true

- name: Do npm install /home/vagrant/checkbox
  npm:
    path: "{{ jenkins_homeuser_path }}/checkbox"

- name: Copy Agent
  copy:
    src: /bakerx/canary/roles/setup/templates/agent
    dest: "{{ jenkins_homeuser_path }}"

- name: Do npm install /home/vagrant/agent
  npm:
    path: "{{ jenkins_homeuser_path }}/agent"

- name: Set environment variable:VMNAME
  lineinfile:
    dest: /etc/environment
    line: VMNAME={{ vmname }}
    regexp: "^VMNAME"
    state: present

- name: Source environment variables
  shell: . /etc/environment

- name: run forever - AGENT and CHECKBOX APP
  shell: |
    cd {{ jenkins_homeuser_path }}/agent
    forever stopall
    forever start index.js
    cd {{ jenkins_homeuser_path }}/checkbox
    git checkout {{branch}}
    forever start index.js
